//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ururtt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class krikduchiEntities : DbContext
    {
        public krikduchiEntities()
            : base("name=krikduchiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Procedure> Procedure { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Sobes> Sobes { get; set; }
        public virtual DbSet<SpisokKlientov> SpisokKlientov { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<ZapisProcedur> ZapisProcedur { get; set; }
    }
}
