//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ururtt
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZapisProcedur
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Fam { get; set; }
        public string Sot { get; set; }
    }
}
